### ISSUE TITLE
Obtain received messages from the sdk

### ISSUE THREAD

**Issue by sof9816** [GleapSDK/Gleap-iOS-SDK#2]
Hello Team, 

We have a case where we want to have the messages when we open the app so that we can update the badge and count inside our app.

What should be done here since the SDK don't provide such function/delegate.

Thanks

**Comment by sof9816** [comment]
Additionally, if this happened we can open the last message that has been sent.

**Comment by boehlerlukas** [comment]
Hey :) Sorry for not getting back to you earlier. We added this feature to our feature requests and will ship it within the next weeks. Thank you so much for contributing to Gleap! I will close the issue here for now as we put it to our internal board. I will notify you once released.
