### ISSUE TITLE
Crash on sendMessageWithData

### ISSUE THREAD

**Issue by sof9816** [GleapSDK/Gleap-iOS-SDK#4]
over 70+ of the users crashed on this function:

```
- (void)sendMessageWithData:(NSDictionary *)data {
    NSError *error;

    <CRASH>
    NSData *jsonData = [NSJSONSerialization dataWithJSONObject: data
                                                       options: 0
                                                         error:&error];
    <CRASH>
   ...
}
```

Mostly happened on iOS 17, but it happened in the lower iOSs as well.

**Comment by boehlerlukas** [comment]
Hey @sof9816 thanks for sharing. Could you also share the crash log? This would be super helpful!

**Comment by boehlerlukas** [comment]
This should be catched in v13.0.0 (will be released later today).
