### ISSUE TITLE
"showBackButton" parameter is ignored

### ISSUE THREAD

**Issue by AlexCogniteq** [GleapSDK/Gleap-iOS-SDK#9]
"showBackButton" parameter is ignored at least in the following APIs: `openFeatureRequests`, `startClassicForm`. No matter what I set "Back" button is always visible.
Gleap SDK 13.9.2, iOS 17.5, Xcode 16 beta 4.

**Comment by boehlerlukas** [comment]
Hey @AlexCogniteq,

thanks a lot for sharing! I'm afraid this is a limitation of the widget itself at the moment (to to a underlaying change of the navigation inside the widget) - we will re-add this feature pretty soon.

**Comment by boehlerlukas** [comment]
@AlexCogniteq a fix will be pushed over the air next week.
